### ISSUE TITLE
disallow

### ISSUE THREAD

**Issue by hjurie** [itgalaxy/robotstxt-webpack-plugin#103]
disallow not apply!

**Comment by evilebottnawi** [comment]
You issue not help to solve problem, please provide example or minimum reproducible test repo

**Comment by hjurie** [comment]
webpack config hm..

const robotsOptions = {
  userAgent: "*",
  disallow: "/"
};

new RobotstxtPlugin(robotsOptions)

but~ build after

robots.txt

User-agent: *
Allow: /

no.. i want 

Disallow: /

**Comment by evilebottnawi** [comment]
Please read how you should set options https://github.com/itgalaxy/generate-robotstxt#usage, you need  `policy`
