### ISSUE TITLE
Error: robotstxt-webpack-plugin@7.0.0: The engine "node" is incompatible with this module. Expected version ">= 10.13.0". Got "8.17.0"

### ISSUE THREAD

**Issue by rseyferth** [itgalaxy/robotstxt-webpack-plugin#106]
As the subject says, when I try to install this package using yarn, it gives an error about expected node versions. I have version 10.15 installed, and tried adding >=10.13 to my own package.json, but to no avail. For now I can get by with `--ignore-engines`, but do you have any idea how to fix this more permanently?

Thanks!

**Comment by evilebottnawi** [comment]
hm, yarn should be good package manager, i don't know why yarn says it, maybe you have globally installed node, try to check it, i think i can't help you here, sorry, but feel free to feedback

**Comment by rseyferth** [comment]
I think you're right, it looks to be a local problem. Thanks for responding!
