### ISSUE TITLE
Compatibility with Webpack 5

### ISSUE THREAD

**Issue by pmankialevich** [itgalaxy/robotstxt-webpack-plugin#120]

**Comment by alexander-akait** [comment]
What is problem? Should work

**Comment by pmankialevich** [comment]
![image](https://user-images.githubusercontent.com/82387437/129707121-0b141f11-fe13-49e7-a3df-85237e5a61cc.png)

**Comment by alexander-akait** [comment]
Feel free to send PR here https://github.com/itgalaxy/robotstxt-webpack-plugin/blob/master/package.json#L76

**Comment by lucasrainett** [comment]
Hi, please have a look, 
https://github.com/itgalaxy/robotstxt-webpack-plugin/pull/122

**Comment by eMtlk** [comment]
Any updates here?

**Comment by alexander-akait** [comment]
Please ping me after holidays, thanks

**Comment by alexanderdavide** [comment]
@lucasrainett @alexander-akait 
Any updates on the new npm version?

**Comment by isakgb** [comment]
Any updates on releasing the new npm version? @alexander-akait

**Comment by alexander-akait** [comment]
Sorry, I don't have time on it, anyway feel free to send a PR

**Comment by lucasrainett** [comment]
PR was sent and merged, it is pending to release to NPM

**Comment by alexander-akait** [comment]
Fixed, release will be soon
