### ISSUE TITLE
Compatibility with Webpack 4

### ISSUE THREAD

**Issue by Vinnl** [itgalaxy/robotstxt-webpack-plugin#76]
[Webpack 4 has been released](https://medium.com/webpack/webpack-4-released-today-6cdb994702d4) - unfortunately, with [a new plug-in infrastructure](https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202). Some helpful tips on migrating plug-ins can be found in [this blog post](https://blog.johnnyreilly.com/2018/01/finding-webpack-4-use-map.html).

(I probably won't be able to find the time to get to know the new plug-in architecture and to submit a pull request, but just in case I or someone else does, I'm filing this issue so there's a place to track it.)

**Comment by evilebottnawi** [comment]
@Vinnl Thanks for issue, i will try to find time on this today :+1:

**Comment by Vinnl** [comment]
Wow, that's a prompt reply - and that would be fantastic, thanks in advance :)

**Comment by evilebottnawi** [comment]
Done in https://github.com/itgalaxy/robotstxt-webpack-plugin/releases/tag/4.0.1 :star: Feel free to feedback

**Comment by Vinnl** [comment]
That was incredibly quick. Although I haven't been able to completely properly test it since some other plugins/loaders have not transitioned yet, it appears to work fine so far. Thanks!
